# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  outputPath: build/

trigger:
- contracts

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '6.x'
  displayName: 'Install Node.js'

- task: CmdLine@2
  inputs:
    script: 'git checkout contracts'
  displayName: 'branch checkout (why?)'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: run prepenv
    customRegistry: 'useNpmrc'
    customEndpoint: npm_repos
  displayName: 'prepenv'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: run build
    customRegistry: 'useNpmrc'
    customEndpoint: npm_repos
  displayName: 'build'

- task: CmdLine@2
  inputs:
    script: 'git update-index --assume-unchanged .npmrc'
  displayName: 'ignore .npmrc change'

- task: Npm@1
  inputs:
    command: 'custom'
    customCommand: run release:ci
    customRegistry: 'useNpmrc'
    customEndpoint: npm_repos
  displayName: 'publish'

- task: PublishPipelineArtifact@0
  displayName: 'copy build output'
  inputs:
    artifactName: 'LambdaFunctions'
    targetPath: '$(outputPath)'
